### ISSUE TITLE
No 32bit build published for 13.0.483

### ISSUE THREAD

**Issue by michela** [sideeffects/HoudiniEngineForUnity_deprecated#1]
README instructions can't be followed. No HAPI folders. No 32bit build published for 13.0.483 as specified in HoudiniVersion.cs

http://www.sidefx.com/index.php?option=com_download&Itemid=208

**Comment by Yelmond** [comment]
What platform are you on? We don't have a 32-bit Mac build. Mac support will come when the 64-bit Unity 5 comes out. I will update the README to clarify.

**Comment by michela** [comment]
Sorted. Win32 build was missing but now has appeared,
