### ISSUE TITLE
HAPI_SaveHIPFile bugged

### ISSUE THREAD

**Issue by waldobronchart** [sideeffects/HoudiniEngineForUnity_deprecated#2]
When I open the saved .hip file, I get an error saying:

"Unexpected end of .hip file"

I'm using 13.0.476

**Comment by Yelmond** [comment]
Looking into it.

**Comment by Yelmond** [comment]
Actually, for me it was crashing or giving some other errors. I found the bug causing my problems and fixed it but I'm not 100% we're looking at the same bug. Please update to 13.0.491 when that is available (late tomorrow) and let me know if you're still having problems.

**Comment by waldobronchart** [comment]
Thanks!
